# Site settings
title: GRDevOps
description: Portfolio of work I have done over the years.  Some of the work is academic while others are either professional or personal.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "/keithlevalley.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Keith Levalley
user_description: Lifelong Software Developer in training
user_title: .Net Developer
email: keith.1985.kl@gmail.com
twitter_username: gr_devops
github_username:  keithlevalley
#gplus_username:  Keith Levalley

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
